// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_HdEmYsBrfcNOnV_F2y3csjQM_S5QqI',
    appId: '1:1022203301496:web:da52b789daabf40472a78d',
    messagingSenderId: '1022203301496',
    projectId: 'songify-699d4',
    authDomain: 'songify-699d4.firebaseapp.com',
    storageBucket: 'songify-699d4.appspot.com',
    measurementId: 'G-46GQCR06HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPvwW8nY2xRUbS4v3pExjEUAkFUGkRZbI',
    appId: '1:1022203301496:android:483132e938f9a33072a78d',
    messagingSenderId: '1022203301496',
    projectId: 'songify-699d4',
    storageBucket: 'songify-699d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZ0fLmvxQA3v4Ognn1BCmH0Wiz54nOYE',
    appId: '1:1022203301496:ios:435f2ac8dea6a6f472a78d',
    messagingSenderId: '1022203301496',
    projectId: 'songify-699d4',
    storageBucket: 'songify-699d4.appspot.com',
    iosBundleId: 'com.example.songify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEZ0fLmvxQA3v4Ognn1BCmH0Wiz54nOYE',
    appId: '1:1022203301496:ios:435f2ac8dea6a6f472a78d',
    messagingSenderId: '1022203301496',
    projectId: 'songify-699d4',
    storageBucket: 'songify-699d4.appspot.com',
    iosBundleId: 'com.example.songify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8_HdEmYsBrfcNOnV_F2y3csjQM_S5QqI',
    appId: '1:1022203301496:web:8ea102a6c6a9507072a78d',
    messagingSenderId: '1022203301496',
    projectId: 'songify-699d4',
    authDomain: 'songify-699d4.firebaseapp.com',
    storageBucket: 'songify-699d4.appspot.com',
    measurementId: 'G-89S88RWFPW',
  );
}
